<?php
  define('LOGGED_IN', 'loggedin');
  define('USERNAME', 'username');
  define('USER_TYPE', 'usertype');
  define('ADMIN', 'admin');
  define('TEACHER', 'teacher');
  define('ORGANISATION', 'organisation');
  define('PROFILE_GET_USERNAME', 'username');
  define('SENDER', 'sender');
  define('DESTINATION', 'destination');
  define('ACTION', 'action');
  define('CONNECT', 'connect');
  define('FOLLOW', 'follow');
  define('BLOCK', 'block');
  define('ACTION_PARAM', 'action_param');
  define('REMOVE', 'remove');
  define('ADD', 'add');
  define('ACCEPT', 'accept');
  define('EDIT_TYPE', 'edit_type');
  define('EDIT_FORM', 'edit_form');
  define('UPDATE_PROFILE', 'update_profile');
  define('UPDATE_PASSWORD', 'update_password');
  define('JOIN_ORGANISATION', 'join_organisation');
  define('EDUCATION_HISTORY', 'education_history');
  define('DELETE_EDUCATION', 'delete_education');
  define('ADD_SKILLS', 'add_skills');
  define('REMOVE_SKILL', 'remove_skill');
  define('DELETE_ACCOUNT', 'delete_account');
 ?>
